import * as fs from 'fs';
import * as path from 'path';

// @illusion: HOOK_CONTENT -> pre-commit hook script that runs code-illusion generate
const HOOK_CONTENT = `#!/usr/bin/env node
// @illusion: pre-commit_generate_artifacts -> runs code-illusion generate on staged source files
// Auto-generated by code-illusion hook install. Re-run to refresh.
const { execSync } = require('child_process');
const path = require('path');

try {
  const cwd = process.cwd();
  const hook = path.join(cwd, '.git', 'hooks', 'pre-commit');

  // Find staged source files within supported paths.
  const staged = execSync('git diff --cached --name-only --diff-filter=ACMR', { cwd, encoding: 'utf8' })
    .split('\\n')
    .filter(Boolean)
    .filter((f) => /\\.[jt]sx?$|\\.[jt]s$|\\.py$|\\.java$|\\.cs$|\\.go$|\\.rs$/.test(f));

  if (staged.length === 0) process.exit(0);

  // Use the repo root as the scan path.
  const repoRoot = execSync('git rev-parse --show-toplevel', { cwd, encoding: 'utf8' }).trim();

  // Only run generate if the CLI is available.
  try {
    const cliPath = require.resolve('code-illusion');
    execSync(\`node "\${cliPath}" generate "\${repoRoot}"\`, { cwd, stdio: 'inherit' });
    console.log('code-illusion: regenerated annotation health artifacts.');
  } catch {
    // CLI not globally installed; try from project node_modules.
    try {
      const localCli = path.join(repoRoot, 'node_modules', '.bin', 'code-illusion');
      if (fs.existsSync(localCli)) {
        execSync(\`"\${localCli}" generate "\${repoRoot}"\`, { cwd, stdio: 'inherit' });
        console.log('code-illusion: regenerated annotation health artifacts.');
      }
    } catch {
      // Silently skip if code-illusion is not available.
    }
  }
} catch {
  // Fail gracefully — don't block commits.
  process.exit(0);
}
`;

// @illusion: install_precommit_hook -> writes pre-commit hook to .git/hooks/pre-commit -> makes executable
export function installPrecommitHook(rootDir?: string): string {
  const dir = rootDir ?? process.cwd();
  const hooksDir = path.join(dir, '.git', 'hooks');
  const hookPath = path.join(hooksDir, 'pre-commit');

  if (!fs.existsSync(hooksDir)) {
    throw new Error(`No .git/hooks directory found at ${hooksDir}. Is ${dir} a git repository?`);
  }

  fs.writeFileSync(hookPath, HOOK_CONTENT, 'utf8');
  // Make executable on posix
  try {
    fs.chmodSync(hookPath, 0o755);
  } catch {
    // Windows: chmod may fail, hook will still work via node shebang
  }

  // Also ensure code-illusion-out/coverage.json is not ignored
  const gitignorePath = path.join(dir, '.gitignore');
  const ciEntry = 'code-illusion-out/cache';
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf8');
    if (!content.split('\n').some((l) => l.trim() === ciEntry)) {
      fs.writeFileSync(gitignorePath, content + (content.endsWith('\n') ? '' : '\n') + ciEntry + '\n', 'utf8');
    }
  }

  return hookPath;
}
